core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quotes/', include('quotes.urls')),
]

quotes/urls.py
from django.urls import path

from .views import home_page_view, about_page_view  # new

app_name = 'quotes'

urlpatterns = [
    path('home/', home_page_view, name='home'),
    path('about/', about_page_view, name='about'),  # new
]

quotes/models.py
from django.db import models


class Quote(models.Model):
    quote = models.TextField()
    writer = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.quote

quotes/views.py
from django.shortcuts import render

from .models import Quote


def home_page_view(request):
    template_name = 'quotes/home.html'
    queryset = Quote.objects.all()
    context = {
        'object_list': queryset
    }
    return render(request, template_name, context)


def about_page_view(request):
    template_name = 'quotes/about.html'
    return render(request, template_name)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/css/uikit.min.css" />
    <title>Django Quotes</title>
</head>
<body>
    <nav class="uk-background-primary uk-margin" uk-navbar>
        <div class="uk-navbar-left">
            <a class="uk-navbar-item uk-logo uk-text-secondary" href="/">Quotes</a>
        </div>
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
                <li>
                    <a href="{% url 'quotes:home' %}" class="uk-text-secondary">
                        Home
                    </a>
                </li>
                <li>
                    <a href="{% url 'quotes:about' %}" class="uk-text-secondary">
                        About
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- 中央よせ -->
    <div class="uk-container">
        {% block content %}
        {% endblock content %}
    </div>
    
    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit-icons.min.js"></script>
</body>
</html>

templates/quotes/about.html
{% extends 'base.html' %}

{% block content %}
<h1 class="uk-heading-divider">About</h1>
{% endblock content %}

templates/quotes/home.html
<!-- templates/quotes/home.html -->
{% extends 'base.html' %}

{% block content %}
<h1 class="uk-heading-divider">Home</h1>

<div>
    {% for object in object_list %}
        <div class="uk-card uk-card-default uk-card-body uk-margin">
            <p>{{ object.quote }}</p>
        </div>
    {% endfor %}
</div>
{% endblock content %}